name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Unzip project
        run: |
          unzip -q remote_monitor_full.zip -d extracted_project

      - name: Find Flutter project
        run: |
          PROJECT_DIR=$(dirname "$(find extracted_project -name pubspec.yaml | head -n 1)")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Flutter project found at: $PROJECT_DIR"

      - name: Fix dependency conflict
        run: |
          cd "$PROJECT_DIR"
          sed -i 's/path: \^1.9.0/path: 1.8.3/g' pubspec.yaml
          sed -i 's/package_info_plus: .*/package_info_plus: 4.2.0/g' pubspec.yaml
          cat pubspec.yaml

      - name: Flutter pub get
        run: |
          cd "$PROJECT_DIR"
          flutter pub get

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          flutter build apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
